language: node_js

node_js:
  - "node"

services:
  - docker

# NOTE: tests will already run as a part of the standard node js setup in travis

before_deploy:
  - docker-compose run package
  - docker-compose build production

deploy:
  provider: script
  script: bash scripts/docker_push
  on:
    branch: master

