language: node_js
sudo: required # This should not be required; for some reason the artifacts are written as root so cannot be deleted

node_js:
  - "node"

services:
  - docker

# NOTE: tests will already run as a part of the standard node js pipeline in travis

before_deploy:
  - docker-compose build --build-arg TRAVIS_COMMIT=$TRAVIS_COMMIT production

deploy:
  provider: script
  script: bash scripts/docker-push
  on:
    branch: master

