FROM node:11

RUN npm install -g webpack

# grab dependencies
WORKDIR /dependencies
COPY package.json package-lock.json /dependencies/
RUN npm install

# build app
WORKDIR /app

COPY src /app/src
COPY build.yml webpack.config.js package.json package-lock.json /app/

RUN cp -a /dependencies/node_modules /app/
RUN npm run build

# write the commit hash to dist/.env, bundle js and copy build.yml
ARG TRAVIS_COMMIT

RUN printf "%s" "BUILD_HASH=$TRAVIS_COMMIT" > /app/.env

CMD eval $(cat .env) node bundle.js
