version: '3.2'

services:

  # local development (watches files)
  develop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TRAVIS_COMMIT
    ports:
      - 8080:8080
    volumes:
      - .:/workspace

  # jest tests
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: "npm test"
    environment:
      - TRAVIS_COMMIT
  # production container
  production:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TRAVIS_COMMIT
    volumes:
      - .:/workspace
    ports:
      - 8080:8080
    command: "node bundle.js"
