version: '3.2'

services:

  # local development (watches files)
  develop:
    build:
      context: .
      dockerfile: Dockerfile-develop
    env_file: .testenv
    ports:
      - 8080:8080
    volumes:
      - .:/workspace

  # jest tests
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file: .testenv
    volumes:
      - .:/workspace

  # production container
  production:
    build:
      context: .
      dockerfile: Dockerfile-production
      args:
        - TRAVIS_COMMIT
    volumes:
      - .:/workspace
    ports:
      - 8080:8080
