version: '3.2'

services:

  # run locally for development (watches files)
  develop:
    build:
      context: .
      dockerfile: Dockerfile-develop
    env_file: .testenv
    ports:
      - 8080:8080
    volumes:
      - .:/workspace

  # run jest tests
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file: .testenv
    volumes:
      - .:/workspace

  # run production artifact
  production:
    build:
      context: .
      dockerfile: Dockerfile-production
    volumes:
      - ./dist:/workspace/dist
    ports:
      - 8080:8080
    environment:
      - TRAVIS_COMMIT
