FROM node:11

RUN npm install -g jest

WORKDIR /app

COPY package.json package-lock.json jest.conf.js ./
COPY src /app/src
COPY test /app/src
COPY build.yml build.yml

RUN npm install && mv /app/node_modules /node_modules
RUN npm install babel-jest

CMD ["npm", "test"]
