FROM node:11

COPY package.json package-lock.json /workspace/

RUN cd /workspace && npm install

ADD . /workspace
WORKDIR /workspace

# write the commit hash to dist/.env, bundle js and copy build.yml
CMD mkdir -p dist && cp build.yml dist/ && printf "%s" "BUILD_HASH=$TRAVIS_COMMIT" > "dist/.env" && npm run build
