#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag innablr_production:latest $DOCKER_USERNAME/innablr_production
docker push $DOCKER_USERNAME/innablr_production
